name: "菠萝包轻小说自动签到"
run-name: "菠萝包轻小说自动签到"
on:
  schedule:
    - cron: "36 1 * * *" # 每天UTC时间10点运行，对应北京时间下午6点
  workflow_dispatch: # 允许手动触发工作流
jobs:
  run-ts-script:
    runs-on: windows-latest
    environment: supabase
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: tsx run
        env:
          SMS_USERNAME: ${{ secrets.SMS_USERNAME }}
          SMS_PASSWORD: ${{ secrets.SMS_PASSWORD }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          REGIST_PASSWORD: ${{ secrets.REGIST_PASSWORD }}
        run: pnpm run checkin

      # # 其他可能的优化步骤
      # - name: Cache node modules
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-
